# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Countries - Royale Ranking
subtitle:           Worldwide Clash Royale ELO-based Rankings.
description:        Worldwide Clash Royale ELO-based Rankings.
keywords:           clash-royale rankings elo rating elo-rating leaderboard games mobile cr clash-royale-api data stats statistics meta best strategy analytics esports players nations countries world worldwide
language:           "en" # default language of the blog. Language codes:
                         # www.w3schools.com/tags/ref_language_codes.asp
baseurl:            ""   # the subpath of your site, e.g. /blog
# the base hostname & protocol for your site. Look at robots.txt as well!
url:                "http://royaleranking.github.io/countries/"
permalink:          /blog/:categories/:title
cover:              
disqus_shortname:   
google_tracking_id: UA-155112132-1
google_ad_client:   ca-pub-3214170672207840

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag